### ISSUE TITLE
在执行文件get.py时报错

### ISSUE THREAD

**Issue by angel8532** [coneypo/Dlib_face_recognition_from_camera#11]
你好楼主：
         向您请教一个问题，在运行“features_extraction_to_csv.py”这个文件是总是报下面的错误。

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
data/data_faces_from_camera/person_2
正在读的人脸图像 / image to read:                data/data_faces_from_camera/person_2/img_face_1.jpg
检测到人脸的图像 / image with faces detected:    data/data_faces_from_camera/person_2/img_face_1.jpg

Traceback (most recent call last):
  File "features_extraction_to_csv.py", line 93, in <module>
    features_mean_personX = return_features_mean_personX(path_images_from_camera + "person_"+str(person+1))
  File "features_extraction_to_csv.py", line 61, in return_features_mean_personX
    features_128d = return_128d_features(path_faces_personX + "/" + photos_list[i])
  File "features_extraction_to_csv.py", line 45, in return_128d_features
    face_descriptor = face_rec.compute_face_descriptor(img_gray, shape)
RuntimeError: The full_object_detection must use the iBUG 300W 68 point face landmark style.
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by coneypo** [comment]
#10

**Comment by coneypo** [comment]
请问还有问题吗？我可以关掉 issue 吗

**Comment by angel8532** [comment]
好的，谢谢啦，没有问题了。

---原始邮件---
发件人: "Xie Zhengtian"<notifications@github.com>
发送时间: 2019年5月10日(星期五) 凌晨1:47
收件人: "coneypo/Dlib_face_recognition_from_camera"<Dlib_face_recognition_from_camera@noreply.github.com>;
抄送: "Author"<author@noreply.github.com>;"angel8532"<85327635@qq.com>;
主题: Re: [coneypo/Dlib_face_recognition_from_camera] 在执行文件get.py时报错 (#11)



#10
 
&mdash;
