### ISSUE TITLE
屏幕中一出现人，就马上退出

### ISSUE THREAD

**Issue by hellowack** [coneypo/Dlib_face_recognition_from_camera#21]
报这个错

IndexError: list assignment index out of range

**Comment by coneypo** [comment]
是在录入人脸还是识别时候报错？可以贴一下完整的log吗；

**Comment by hellowack** [comment]
E:\Anaconda3\envs\tensorflow_env\python.exe E:/PythonFiles/Dlib_face_recognition_from_camera-master/Dlib_face_recognition_from_camera-master/face_reco_from_camera.py
Faces in Database： 1
##### camera person 1 #####
Traceback (most recent call last):
with person 1 the e distance: 0.4047276480891428
  File "E:/PythonFiles/Dlib_face_recognition_from_camera-master/Dlib_face_recognition_from_camera-master/face_reco_from_camera.py", line 222, in <module>
Minimum e distance with person Person_1
Unknown person


    main()
  File "E:/PythonFiles/Dlib_face_recognition_from_camera-master/Dlib_face_recognition_from_camera-master/face_reco_from_camera.py", line 218, in main
    Face_Recognizer_con.run()
  File "E:/PythonFiles/Dlib_face_recognition_from_camera-master/Dlib_face_recognition_from_camera-master/face_reco_from_camera.py", line 210, in run
    self.process(cap)
  File "E:/PythonFiles/Dlib_face_recognition_from_camera-master/Dlib_face_recognition_from_camera-master/face_reco_from_camera.py", line 192, in process
    self.modify_name_camera_list()
  File "E:/PythonFiles/Dlib_face_recognition_from_camera-master/Dlib_face_recognition_from_camera-master/face_reco_from_camera.py", line 115, in modify_name_camera_list
    self.name_known_list[1] ='李四'.encode('utf-8').decode()
IndexError: list assignment index out of range

Process finished with exit code 1

**Comment by hellowack** [comment]
是因为代码初始设置了两个名字吗，我现在注释掉了第二个名字“李四”，然后显示正常了

**Comment by coneypo** [comment]
> 是因为代码初始设置了两个名字吗，我现在注释掉了第二个名字“李四”，然后显示正常了

嗯嗯是的
    # 修改显示人名
    def modify_name_camera_list(self):
        # Default known name: person_1, person_2, person_3
        self.name_known_list[0] ='张三'.encode('utf-8').decode()
        self.name_known_list[1] ='李四'.encode('utf-8').decode()
        # self.name_known_list[2] ='xx'.encode('utf-8').decode()
        # self.name_known_list[3] ='xx'.encode('utf-8').decode()
        # self.name_known_list[4] ='xx'.encode('utf-8').decode()

你如果只存了一个人，那 name_known_list[1] 就无法检索所以会报错。。。

**Comment by hellowack** [comment]
谢谢大佬的回答，突然感觉问题有点low，hhh

**Comment by coneypo** [comment]
> 谢谢大佬的回答，突然感觉问题有点low，hhh

嗯嗯如果没有其它问题，我就把 Issue 关了哈

**Comment by hellowack** [comment]
嗯嗯，好的
