### ISSUE TITLE
problems about "from skimage import io"

### ISSUE THREAD

**Issue by keke1229488344** [coneypo/Dlib_face_recognition_from_camera#38]
Logs
---
C:\Users\FXIT\Documents\VsCodeProject\python_face\Dlib_face_recognition_from_camera-master>python features_extraction_to_csv.py
Traceback (most recent call last):
  File "features_extraction_to_csv.py", line 13, in <module>
    from skimage import io
  File "C:\Users\FXIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\skimage\io\__init__.py", line 11, in <module>
    from ._io import *
  File "C:\Users\FXIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\skimage\io\_io.py", line 4, in <module>
    from ..color.colorconv import rgb2gray, rgba2rgb
  File "C:\Users\FXIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\skimage\color\__init__.py", line 1, in <module>
    from .colorconv import (convert_colorspace,
  File "C:\Users\FXIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\skimage\color\colorconv.py", line 56, in <module>
    from scipy import linalg
  File "C:\Users\FXIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\__init__.py", line 130, in <module>
    from . import _distributor_init
  File "C:\Users\FXIT\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。

**Comment by coneypo** [comment]
这是环境的问题。。。和这个 repo 没关系，你先在 windows 下面把环境搭好 :)
