### ISSUE TITLE
Python 3.10 环境下dlib 安装失败，有解决方法吗

### ISSUE THREAD

**Issue by Jzow** [coneypo/Dlib_face_recognition_from_camera#62]
错误日志：

当我尝试运行命令
`pip install -r requirements.txt`

```python
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-uqqynw0g\dlib_65cc5aedee914588a27b0caca8163f3c\setup.py", line 223, in <module>
          setup(
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\command\install.py", line 68, in run
          return orig.install.run(self)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\install.py", line 698, in run
          self.run_command('build')
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-uqqynw0g\dlib_65cc5aedee914588a27b0caca8163f3c\setup.py", line 129, in run
          cmake_version = self.get_cmake_version()
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-uqqynw0g\dlib_65cc5aedee914588a27b0caca8163f3c\setup.py", line 122, in get_cmake_version
          raise RuntimeError("\n*******************************************************************\n" +
      RuntimeError:
      *******************************************************************
       CMake must be installed to build the following extensions: dlib
      *******************************************************************

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of dlib
  Moving to c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages\_dlib_pybind11.cp310-win_amd64.pyd
   from C:\Users\Administrator\AppData\Local\Temp\pip-uninstall-oa5s4swl\_dlib_pybind11.cp310-win_amd64.pyd
  Moving to c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages\dlib-19.22.99.dist-info\
   from C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\~lib-19.22.99.dist-info
  Moving to c:\users\administrator\appdata\local\programs\python\python310\lib\site-packages\dlib\
   from C:\Users\Administrator\AppData\Local\Programs\Python\Python310\Lib\site-packages\~lib
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> dlib

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by qinkaiyue** [comment]
换py3.5

**Comment by coneypo** [comment]
windows下用anaconda装dlib
